### ISSUE TITLE
info which radiant triggered not written out correctly

### ISSUE THREAD

**Issue by shallmann** [barawn/firmware-radiant#11] opened 2022-07-15 16:11 UTC
We are not sure if In the firmware, the information which of the radiant triggers triggered is written out correctly. While non-radiant events have  all `-128` , three additional values exist in the output files: `-1, 0, 1`. I am expecting only 2, no idea what the -1 means. Is the flag different when both RF have triggered? Otherwise: Should be fixed, since we now switched to running with two radiant triggers on the upward and on the downward facing lpdas.

**Comment by jakobhenrichs** [comment] 2022-07-20 08:02
The plot shows the contribution of the different trigger flags (0,1,-1) to the total number of triggered events with the surface channels.
![trigger_rate_station21_last7days](https://user-images.githubusercontent.com/100706809/179929566-f963bf21-a438-42ee-a339-beb2c5db6774.png)

**Comment by shallmann** [comment] 2022-07-20 08:03
For completeness, here is where the -1, 0, 1 are written out in Mattak...

https://github.com/RNO-G/mattak/blob/main/src/Header.cc#L44

... might the events triggered by both RF 0 and RF 1 get a different trigger flag?

And from a mail by @cozzyd:
... there could theoretically be some events that are labeled as both soft triggers and rf triggers? Probably the condition for rf_trigger should be !(SOFT | PPS) instead...  I'll think about how to clean up this logic for those edge cases.

**Comment by jakobhenrichs** [comment] 2022-07-20 08:49
We had a look at the data and if a -1 is written out, no other trigger (lt or forced) fired.

**Comment by cozzyd** [comment] 2022-07-27 05:47
As a clarification (since this issue is in the firmware repository), there are 3 data formats involved here:

1) the firmware header (the only thing relevant to this repository), defined (sorta) here: https://github.com/RNO-G/firmware-radiant/blob/master/hdl/radiant_event_ctrl.v
2) the DAQ data format header (defined in `librno-g`, here is where the flags are copied from the firmware header to the DAQ format header: https://github.com/RNO-G/librno-g/blob/master/src/radiant.c#L669 )  
3) the archival data format header (defined in `mattak`, here is where we read in the trigger bits: https://github.com/RNO-G/mattak/blob/main/src/Header.cc#L44, note in the current implementation, to be fixed, rf_trigger is unreliable for the reasons below)

The number assignments for `which_radiant_trigger` are done in mattak, based on the available RADIANT bits (RADIANT_RF0, RADIANT_RF1, RADIANT_INTERNAL_COPY which I call RADIANTX...) from the firmware (which are mirrored into the DAQ data format).

The issue is that the RF0 and RF1 bits are set unreliably in the firmware. Sometimes they fail to be set (but RADIANTX is still high, indicating that it was indeed a RADIANT trigger), and sometimes they are stuck high, so the RADIANT_RF0 or RADIANT_RF1 bit might be high even in a force trigger.

 In the archival format I assigned `which_radiant_trigger` to 0 if RADIANT_RF0 and RADIANTX are set, 1 if RADIANT_RF1 and RADIANTX are set, -1 if in the case of RADIANTX being set but neither RADIANT_RF0 or RADIANT_RF1 and -128 if RADIANTX is not set. I do not check if both RADIANT_RF0 and RADIANT_RF1 are high so that would be marked as 0 because of the order. The bits are available in the DAQ format so it would be straightforward to check if it ever happens (though... if it does happen, I wouldn't be convinced that it's not because one of the bits got stuck high...).

**Comment by barawn** [comment] 2022-07-27 14:38
The actual trigger bits come from

https://github.com/RNO-G/firmware-radiant/blob/master/hdl/trig/radiant_trigger_overlord.sv

**Comment by barawn** [comment] 2022-07-27 15:01
I think there's some confusion here regarding the trigger bits as well: bits[1:0] are not "trigger bits" on their own. They're *clarifying* bits: when bit 5 is set, bits [1:0] indicate which one is valid. 

Bits[1:0] are *only captured* when the flag which causes an internal trigger to occur is set. So if an RF1 trigger occurs, bits[1:0] will indicate "RF1". But then if you do a soft trigger afterwards, bits[1:0] should still indicate RF1 (and bit 5 will not be set). That doesn't indicate another RF1. It's just the former state. I can get rid of that behavior pretty trivially if need be. You can see this behavior in https://github.com/RNO-G/firmware-radiant/blob/master/hdl/radiant_trig_top.v - the trigger type bits are captured when the flag crosses, and never reset.

The "unreliability" part (bit 5 set with no bit [1:0]) is due to the fact that there's a clock-crossing involved: the RF trigger operates in a much faster clock domain, so it's tricky to ensure that the original bits are still in the same state as they were by the time the OR of the two reaches the other clock domain - there's no way to write complicated timing constraints like "make sure this bit clocked by clock A gets to this guy clocked by clock B within 1 clock of clock B for all relative phases of clock A/B." There's probably some small window where I've got it screwed up.

The way I wrote the logic tried to focus on making sure the generating trigger gets captured as often as possible. I can change it so that it's a little different, namely "guarantee you capture any RF trigger that occurs." There's a way to think about this in terms of false positive/false negative I think but I can't think about it now.

**Comment by cozzyd** [comment] 2022-07-27 16:28
There's no need to change this logic in firmware, much easier for me to change the interpretation (ignore those bits if bit 5 is not set). (I probably got confused about the intended meaning because bit 5 was added later).

Thanks,
-Cosmin

**Comment by barawn** [comment] 2022-07-27 17:45
OK, great. Unless I *really* screwed something up bits[5:2] should be reliable, it's just [1:0] that are iffy. Let me know if they're too iffy and I can stretch the period that they're held stable.

**Comment by barawn** [comment] 2023-06-07 15:09
Close as won't fix since there wasn't really anything wrong.

**Closed as completed** 2023-06-07 15:09 UTC
Labels: bug, question, wontfix
